# Correlation


### Pearson

$$\begin{equation}
\frac{\sum_{i=1}^n(X_i - \bar{X})(Y_i - \bar{Y})}{\sqrt(\sum_{i=1}^n(X_i - \bar{X})^2)\sum_{i=1}^n(Y_i - \bar{Y}^2)}
\end{equation}$$

```{r}
x=c(44.4,45.9, 41.9,53.3,44.7,44.1,50.7,45.2,60.1)
y=c(2.6,3.1,2.5, 5.0,3.6,4.0,5.2,2.8, 3.8);
plot(x,y,las=1)
n=length(x)
mx=mean(y); my=mean(y)
sum((x-mx)*(y-my))/(sd(x)*sd(y)*(n-1)); cov(x,y)/(sd(x)*sd(y))
## [1] 0.5711816
## [1] 0.5711816
cor(x,y)
## [1] 0.5711816
cor(x,y,method="pearson")
cor.test(x,y,method="pearson",alternative="g")

pr=cor(x,y); stat=pr*sqrt((n-2)/(1-pr^2))
c(stat , pt(stat,n-2,lower.tail=F) )

z=(-10):10; cor(z,z^2)
## [1] 0
plot(z,z^2,las=1,ylab=expression(z^2))

```



### Kendall

$$\begin{equation}
K = \sum_{i=1}^{n-1}\sum_{j=i+1}^{n}Q[(X_i, Y_i),(X_j,Y_j)]
\end{equation}$$

```{r}
cor(x,y,method="kendal")
## [1] 0.4444444
cor.test(x,y,method = "kendall",alternative="g")
n2=n*(n-1)/2; oy=outer(y,y,"-"); z=oy[lower.tri(oy)]
ox=outer(x,x,"-"); w=ox[lower.tri(ox)]
Tstat=sum(z*w>0); Tstat
K=2*Tstat-n2 # K=T- [n(n-1)/2-T] ; K/n2
sdk=sqrt(2*n2*(2*n+5)/18); K/sdk
pnorm(K/sdk,lower.tail=F);
## [1] 0.04764642
cor.test(x,y,method = "kendall",exact=F,alternative="g")

```




### Spearman Rank

$$\begin{equation}

\end{equation}$$

```{r}
rx=rank(x); ry=rank(y)
cor(x,y,method="spearman")
cor(rx,ry)
cor.test(x,y,method="spearman",alternative="g")

```





### Cohen's kappa

$$\begin{equation}

\end{equation}$$

```{r}
library(psych); n=100
data=cbind(c(0.75,0.05,0),c(0.01,0.04,0),
c(0.04,0.01,0.1))
cohen.kappa(x=data*n)

```